display_name: 星链
publisher_display_name: 星链
identity_name: starlink.app
msix_version: 1.1.2.0
logo_path: windows\runner\resources\app_icon.ico
capabilities: internetClient, internetClientServer, privateNetworkClientServer
languages: en-us, zh-cn, zh-tw, ru-ru, tr-tr
protocol_activation: starlink
execution_alias: starlink
certificate_path: windows\sign.pfx
certificate_password:
publisher: CN=8CB43675-F44B-4AA5-9372-E8727781BDC4
install_certificate: "false"
enable_at_startup: "true"
startup_task:
  parameters: --autostart
