app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: starlinkvpn
publisher_url: https://github.com/hiddify/hiddify-next
display_name: starlinkvpn
executable_name: starlinkvpn.exe
output_base_file_name: starlinkvpn-Windows-Setup-x64
create_desktop_icon: true
install_dir_name: "{autopf64}\\starlinkvpn"
setup_icon_file: ..\..\windows\runner\resources\app_icon.ico
locales:
  - zh
script_template: inno_setup.sas
