app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: 星链
publisher_url: https://github.com/hiddify/hiddify-next
display_name: 星链
executable_name: Hiddify.exe
output_base_file_name: hiddify-1.1.2+20507-windows-setup_exe
create_desktop_icon: true
install_dir_name: "{autopf64}\\Hiddify"
setup_icon_file: D:\a\xignlian-csze2024\xignlian-csze2024\windows\runner\resources\app_icon.ico
locales:
  - en
script_template: inno_setup.sas
