app_id: com.starlinkvpn.app
publisher: starlinkvpn
publisher_url: https://github.com/hiddify/hiddify-next
display_name: starlinkvpn
executable_name: Hiddify.exe
output_base_file_name: 星链-Windows-x64
create_desktop_icon: true
install_dir_name: "{autopf64}\\starlinkvpn"
setup_icon_file: ..\..\windows\runner\resources\app_icon.ico
locales:
  - zh
script_template: inno_setup.sas
